// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-guide/AudiencePositioning.tsx": () => import("../components/mockups/brand-guide/AudiencePositioning.tsx"),
  "./components/mockups/brand-guide/BrandVoice.tsx": () => import("../components/mockups/brand-guide/BrandVoice.tsx"),
  "./components/mockups/brand-guide/ColorSystem.tsx": () => import("../components/mockups/brand-guide/ColorSystem.tsx"),
  "./components/mockups/brand-guide/DesignPatterns.tsx": () => import("../components/mockups/brand-guide/DesignPatterns.tsx"),
  "./components/mockups/brand-guide/LogoIdentity.tsx": () => import("../components/mockups/brand-guide/LogoIdentity.tsx"),
  "./components/mockups/brand-guide/Typography.tsx": () => import("../components/mockups/brand-guide/Typography.tsx")
};
